server:
  port: 8080
  servlet:
    context-path: /users

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quanlynguoidung
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.springframework.web: DEBUG
    org.hibernate: INFO

